# Header
menu:
  Home: /
  Archives: /archives
  Wiki: https://wiki.imciel.com
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# Links
links:
  主题作者: http://xiguabaobao.com
  热前端: http://reqianduan.com

# Miscellaneous
google_analytics: UA-51259806-3
favicon: /favicon.png
twitter: cielpy5
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: imciel

# Baidu share
baidushare: true
